
    create table funcionario (
       id int8 generated by default as identity,
        nascimento date,
        salario numeric(10, 2),
        num_dep int4,
        nome varchar(255),
        primary key (id)
    );
